input_dir: "/home/frc-ag-3/harry_ws/visual_synthesis/final_project/data/flickr/structures/regular_dataset"
output_dir: "/home/frc-ag-3/harry_ws/visual_synthesis/repos/swapping-autoencoder-pytorch/datasets/flickr_data_v0_tmp"
gan_augment: False
train_test_split: "80:20"
img_size: 224
num_classes: 5
classes: 
  - label: 0
    class_name: "forest"
    class_dirs:
      - "forest_trees"
    

  - label: 1
    class_name: "mountain"
    class_dirs:
      - "mountain_landscape"
      - "glacier"

  - label: 2
    class_name: "sea"
    class_dirs:
      - "sea"

  - label: 3
    class_name: "desert"
    class_dirs:
      - "desert_landscape"

  - label: 4
    class_name: "city"
    class_dirs:
      - "city"
